backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/uploads"
public_folder: "/uploads"
collections:
  - name: posts
    label: Posts
    folder: _src/posts
    create: true
    slug: "{{slug}}"
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Date', name: 'date', widget: 'datetime'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
